src/java/bean/Loggin.java
package bean;

import clases.InterfaceBean;
import clases.Usuarios;
import static clases.InterfaceBean.session;
import com.sun.xml.ws.developer.Serialization;
import controllers.UsuariosController;
import java.io.IOException;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import facade.UsuariosFacade;

@ManagedBean(name = "loggin")
@SessionScoped
@Serialization
public class Loggin implements InterfaceBean {

    private String cedula;
    private int ced;
    private String contrasena;
    private Usuarios usrActual;
    private String usrTipo;

   
    @EJB
    UsuariosFacade usr;

    public Loggin(String cedula, String contrasena) {
        this.cedula = cedula;
        this.contrasena = contrasena;
    }

    public Usuarios getUsrActual() {
        return usrActual;
    }
    public void irPerfil() throws IOException{
        FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/faces/perfiles.xhtml");
    }

    public void setUsrActual(Usuarios usrActual) {
        this.usrActual = usrActual;
    }
    
    public Loggin() {
    }

     public String getUsrTipo() {
        return usrTipo;
    }

    public void setUsrTipo(String usrTipo) {
        this.usrTipo = usrTipo;
    }
    public int getCed() {
        return ced;
    }

    public void setCed(int ced) {
        this.ced = ced;
    }

    public String getCedula() {
        return cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getContrasena() {
        return contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public boolean isActiva() {
        return session.isActiva();

    }

    public boolean isAdmin(){
        try {
            
        int tipoUst = UsuariosController.getCurrent().getUsrTipo();
        return tipoUst==1;
        } catch (Exception e) {
             FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", ""+e+"\nLocalización: "+e.getLocalizedMessage()));
        }
        return false;
    }
    
    public void comprobar() {


        try {
            Usuarios user;
            int ced = Integer.parseInt(cedula);
            user = (Usuarios) usr.find(ced);
            if (user != null && user.getUsrPass().trim().matches(contrasena)) {
                UsuariosController.setCurrent(user);
                usrActual=usuarioActual();
                setUsrActual(usrActual);
                FacesContext context2 = FacesContext.getCurrentInstance();
                HttpSession sessionv = (HttpSession) context2.getExternalContext().getSession(true);
                sessionv.setAttribute("user", usrActual);
                session.setActiva(true);
                //FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/");
                irA("perfil");
            } else {
                FacesContext context = FacesContext.getCurrentInstance();
                context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Verifique cédula y/o contraseña!", ""));

            }
        } catch (Exception e) {
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Verifique cédula y/o contraseña!  " + e, ""));
            System.out.println("Excepcion!!!....");
        }


    }
    public Usuarios usuarioActual(){
        return  UsuariosController.getCurrent();
    }

    public void cerrarSesion() throws IOException {

        UsuariosController.getCurrent().setUsrCc(null);
        UsuariosController.setCurrent(new Usuarios());
        session.setActiva(false);
        FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/");
    }

    public void irA(String dire) throws IOException{
        switch(dire){
            case "index": FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/"); break;
            case "perfil": FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/faces/web/pages/perfiles.xhtml"); break; 
            case "contacto": FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/faces/web/pages/contactenos.xhtml"); break;    
            case "regVacante": FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/faces/registrarVacante.xhtml"); break;    
        }
    }
    
    public void validarUsuario() throws IOException {

        if (usr.validarLogueo(cedula, contrasena)) {
            
        } else {
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Verifique cédula y/o contraseña!", ""));

        }
    }


 
//Hay un problema con el redireccionamiento. Me tocó poner la dirección faces/crearUsuario.xhtml en lugar de red_dinamica/crearUsuario.xhtml para que
//pudiera funcionar.

    public void solicitarInscripcion() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Ingreso", "Bienvenido " + cedula));
        context.addMessage(null, new FacesMessage("Second Message", "Additional Info Here..."));
        FacesContext.getCurrentInstance().getExternalContext().redirect("componentes/registro_usr.xhtml");

    }
   
}

src/java/bean/PhotoCamBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import clases.InterfaceBean;
import static clases.InterfaceBean.session;
import clases.Usuarios;
import controllers.UsuariosController;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.FacesException;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.imageio.stream.FileImageOutputStream;
import javax.servlet.ServletContext;
import org.primefaces.context.RequestContext;
import org.primefaces.event.CaptureEvent;
import facade.UsuariosFacade;
 
@ManagedBean(name="photoCamBean")
@ViewScoped
public class PhotoCamBean implements InterfaceBean, Serializable{
 
 @EJB
 private UsuariosFacade ejbUsuariosFacade;
    
    public void oncapture(CaptureEvent captureEvent) throws IOException, InterruptedException {
         // obtenemos los datos de la foto como array de bytes
        final byte[] datos = captureEvent.getData();
 
        final ServletContext servletContext = (ServletContext)FacesContext.getCurrentInstance().getExternalContext()
                .getContext();
        //asignamos un nombre a la foto segun el usuario actual.
        String foto = UsuariosController.getCurrent().getUsrCc()+ ".png"; 
        
        FacesContext context = FacesContext.getCurrentInstance(); 
       // context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Foto dir = "+foto, "Foto dir = "+foto));
        
        //final String fileFoto = "C:\\red_dinamica\\web\\Recursos\\Imagenes\\perfil\\"+ foto;//para Stip
        final String fileFoto = "C:\\WebApplication1\\WebApplication1\\web\\Recursos\\Imagenes\\perfil\\"+ foto;//para oscar
        //Alteramos el valor de UsrCC para el usuario actual con el fin de usar ese valor para rellenar el campo de imagen en el formulario
        
        System.out.println(fileFoto);
        
        File archivo = new File(fileFoto);
        archivo.delete();
        FileImageOutputStream outputStream = null;
        try {
            outputStream = new FileImageOutputStream(new File(fileFoto));
            // guardamos la imagen
            outputStream.write(datos, 0, datos.length);
            FacesContext.getCurrentInstance().getExternalContext().wait(5);
            FacesContext.getCurrentInstance().getExternalContext().redirect("/red_dinamica/faces/perfiles.xhtml");
        } catch (IOException e) {
            throw new FacesException("Error guardando la foto.", e);
        } finally {
            try {
                outputStream.close();
            } catch (IOException e) {
            }
        }
                
        if(SessionBean.session.isActiva()){
          
          context.addMessage(null, new FacesMessage("Cierre sesión", "Imagen cargada exitosamente. Inicie sesión nuevamente para efectuar cambios"));
          
        }
       
    }
 
    public boolean isVerFoto() {
        
        final ServletContext servletContext = (ServletContext)FacesContext.getCurrentInstance().getExternalContext().getContext();
        Usuarios u = UsuariosController.getCurrent();
        String foto = ""+u.getUsrCc();
        
        String fileFoto = servletContext.getRealPath("") + File.separator + "/Recursos/Imagenes/perfil/" + File.separator + foto;
        
        File file = new File(fileFoto);
        return file.exists();
        //return foto.equals(idUsuario);
           
        
    }
    //Arreglarlo
    public boolean isTieneFoto(){
     Usuarios u = UsuariosController.getCurrent();
        String foto = ""+u.getUsrCc();
        String idUsuario = ""+u.getUsrCc()+".png";   
        int valor = 0;
        if(foto.equals(idUsuario)){
            valor = 1;
            return true;
        }
        else return false;
    }
}

src/java/controllers/AmigosController.java
package controllers;

import clases.Amigos;
import util.JsfUtil;
import util.PaginationHelper;
import facade.AmigosFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("amigosController")
@SessionScoped
public class AmigosController implements Serializable {

    private Amigos current;
    private DataModel items = null;
    @EJB
    private facade.AmigosFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AmigosController() {
    }

    public Amigos getSelected() {
        if (current == null) {
            current = new Amigos();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AmigosFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Amigos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Amigos();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AmigosCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Amigos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AmigosUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Amigos) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AmigosDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Amigos getAmigos(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Amigos.class)
    public static class AmigosControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AmigosController controller = (AmigosController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "amigosController");
            return controller.getAmigos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Amigos) {
                Amigos o = (Amigos) object;
                return getStringKey(o.getAmigoId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Amigos.class.getName());
            }
        }
    }
}

web/componentes/banner.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      lang="es"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
        <link rel="stylesheet" type="text/css" href="../Recursos/Css/general.css" />
        <!-- Start WOWSlider.com HEAD section -->
        <link rel="stylesheet" type="text/css" href="../Recursos/Banner/engine1/style.css" media="screen" />
        <script type="text/javascript" src="../Recursos/Banner/engine1/jquery.js"></script>
        <!-- End WOWSlider.com HEAD section -->

    </h:head>

    <h:body>
 
<!--        <h:form style="border: 1px #3a4f54 solid" class="banner">-->
                <!-- Start WOWSlider.com BODY section id=wowslider-container1 -->
                <div id="wowslider-container2" style="height: 200px; width: 800px;">
                    <div class="ws_images">
                        <ul>
                            <li>
                                <h:graphicImage  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Banner/data1/images/1.jpg" style="float:left" id="wows2_0">
                                </h:graphicImage>
                                Ultimas noticias
                            </li>
                            <li>
                                <h:graphicImage  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Banner/data1/images/2.jpg" style="float:left" id="wows2_1">
                                </h:graphicImage>
                            </li>
                            <li>
                                <h:graphicImage  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Banner/data1/images/3.jpg" style="float:left" id="wows2_2">
                                </h:graphicImage>
                            </li>
                            <li>
                                <h:graphicImage  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Banner/data1/images/4.jpg" style="float:left" id="wows2_3">
                                </h:graphicImage>
                            </li>
                        </ul>
                    </div>
                    <div class="ws_thumbs">
                        <div>
                            <a href="#" title=""><img src="#{bundle.UrlProyecto}Recursos/Banner/data1/tooltips/59726_296322510497938_1225728488_n.jpg" alt="" /></a>
                            <a href="#" title=""><img src="#{bundle.UrlProyecto}Recursos/Banner/data1/tooltips/846_50825808784_6381_n.jpg" alt="" /></a>
                            <a href="#" title=""><img src="#{bundle.UrlProyecto}Recursos/Banner/data1/tooltips/923289_369100159868062_2012289493_n.jpg" alt="" /></a>
                            <a href="#" title=""><img src="#{bundle.UrlProyecto}Recursos/Banner/data1/tooltips/1233952_10201820552577323_1683792721_n.jpg" alt="" /></a>
                        </div>
                    </div>
                </div>
                <script type="text/javascript" src="#{bundle.UrlProyecto}Recursos/Banner/engine1/wowslider.js"></script>
                <script type="text/javascript" src="#{bundle.UrlProyecto}Recursos/Banner/engine1/script.js"></script>
                
                <a href="#" class="ws_frame"></a>
                <div class="ws_shadow"></div>
                <!-- End WOWSlider.com BODY section -->
            <!--</h:form>-->
       </h:body>

</html>

web/componentes/iniciarSesion.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      lang="es"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <link rel="stylesheet" type="text/css" href="../Recursos/Css/general.css" />
    </h:head>
    <h:body>
        <h:form style="border: 1px #3a4f54 solid" class="iniciarsesion" id="formIniciarSesion">
            <p:messages id="msgs" />
            <p:growl id="growl" showDetail="true" /> 
            <h:panelGrid columns="3">
                <h:outputLabel for="cedula" value="Cédula: *" />
                <h:inputText id="cedula" value="#{loggin.cedula}" rendered="true" >
                    <f:validateLength minimum="3" />  
                    <f:validateRequired />  
                    <p:ajax update="msgCedula,growl" event="keyup"/>
                </h:inputText>
                <p:message for="cedula" id="msgCedula" display="tooltip" />  
                 <h:outputLabel value="Contraseña: *" for="pass" />
                 <p:password id="pass" value="#{loggin.contrasena}"   required="true">
                   <f:validateLength minimum="3" />  
                   <f:validateRequired /> 
                   <p:ajax update="msgPass,growl" event="keyup" />
                 </p:password>
                 <p:message for="pass" id="msgPass" display="tooltip" />  
                                  
           </h:panelGrid>
            <p:commandButton value="Ingresar" actionListener="#{loggin.comprobar()}" update="msgs"/> 
         </h:form>
     </h:body>
</html>

web/componentes/menugeneral.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      lang="es"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <link rel="stylesheet" type="text/css" href="/Recursos/Css/general.css" />
    </h:head>

    <h:body>
        
            <h:form class="Titulo">
                    <p>
                    <h:graphicImage id="logo"  alt="Red Colombiana de Dinámica de Sistemas" url="Recursos/Imagenes/logoredDS.jpg" style="float:left">
                    </h:graphicImage>  

                    <p> <h1>Red Colombiana de Dinámica de Sistemas</h1>
                    </p> 
                </p>
                <br></br> <br></br>    
                <p:breadCrumb>  
                    <p:menuitem value="Inicio" actionListener="#{loggin.irA('index')}" />  
                    <p:menuitem value="Inicio" actionListener="#{loggin.irA('index')}" />
                    <p:menuitem value="Contáctenos" actionListener="#{loggin.irA('contacto')}" />  
                </p:breadCrumb>  
           </h:form>
    </h:body>

</html>

web/componentes/menuregistro.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      lang="es"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <link rel="stylesheet" type="text/css" href="../Recursos/Css/general.css" />
    </h:head>

    <h:body>
        
        <h:form class="Titulo">
                    <p>
<!--                 Alternativamente puede ser:   <h:graphicImage id="logo"  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Imagenes/logoredDS.jpg" style="float:left">
                    </h:graphicImage>    -->
                        
                    <h:graphicImage id="logo"  alt="Red Colombiana de Dinámica de Sistemas" url="/Recursos/Imagenes/logoredDS.jpg" style="float:left">
                    </h:graphicImage>  

                    <p> <h1> Red Colombiana de Dinámica de Sistemas</h1>
                    </p> 
                </p>
                <br></br> <br></br>    
                <p:breadCrumb>  
                    <p:menuitem value="Inicio" actionListener="#{loggin.irA('index')}"/>  
                    <p:menuitem value="Inicio" actionListener="#{loggin.irA('index')}"/>  
                    
                    <p:menuitem value="Perfil" actionListener="#{loggin.irA('perfil')}" rendered="#{loggin.activa}"/> 
                    <p:menuitem value="Contáctenos" actionListener="#{loggin.irA('contacto')}" />  
                </p:breadCrumb>  
           </h:form>
        
    </h:body>

</html>

web/componentes/perfil.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      lang="es"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
        <link rel="stylesheet" type="text/css" href="../Recursos/Css/general.css" />
        <link rel="stylesheet" type="text/css" href="" />
    </h:head>

    <h:body>
        <h:form id="perfil" title="Perfil">  
            <p:panel menuTitle="Perfil">
                <h:panelGrid columns="2">
                    <p:graphicImage id="imagendePerfil" value="/faces/Recursos/Imagenes/perfil/#{usuariosController.selected.usrCc}" cache="false" rendered="#{photoCamBean.tieneFoto}" style="height: 80px;"/>
                    <p:graphicImage id="imagendePerfil2" value="/faces/Recursos/Imagenes/perfil/default.png" cache="false" rendered="#{!photoCamBean.tieneFoto}" style="height: 80px;"/>
                    
                    <h:outputLabel for="nombre" class="destacado" value="#{loggin.usuarioActual().usrNombres} #{loggin.usuarioActual().usrApellidos}" />
                    <p:commandLink  actionListener="#{loggin.irA('index')}">
                        <p:graphicImage value="Inicio" url="/faces/Recursos/Imagenes/inicio_p.png" style="height: 45px;"/>  
                    </p:commandLink>
                    <p:commandLink value="Mi perfil" actionListener="#{loggin.irA('perfil')}"></p:commandLink>
                    <p:commandLink value="Cerrar sesión" actionListener="#{loggin.cerrarSesion()}"></p:commandLink>
                    </h:panelGrid>
            </p:panel>
        </h:form>  

    </h:body>

</html>